# Generated by Django 5.2 on 2025-04-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(max_length=32, verbose_name='Расцветка')),
                ('stuff_type', models.CharField(choices=[('hoodie', 'капюшонка'), ('jeans', 'жинсы'), ('t-shirt', 'футболка'), ('longsleeve', 'лонгслив'), ('dress', 'юбка'), ('outerwear', 'верхняя одежда'), ('others', 'другое')], max_length=16, verbose_name='Тип')),
                ('stuff_size', models.CharField(choices=[('xxs', 'Xxs'), ('xs', 'Xs'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'Xl'), ('xxl', 'Xxl'), ('one size', 'один размер')], max_length=16, verbose_name='Размер')),
                ('price', models.PositiveBigIntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('city', models.CharField(max_length=32, null=True, verbose_name='Город')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
